export { angle } from './Compare.demo.angle';
export { codeSyntax } from './Compare.demo.code';
export { configurator } from './Compare.demo.configurator';
export { dragBounds } from './Compare.demo.dragBounds';
export { fixed } from './Compare.demo.fixed';
export { horizontal } from './Compare.demo.horizontal';
export { hover } from './Compare.demo.hover';
export { stylesApi } from './Compare.demo.stylesApi';
export { withImage } from './Compare.demo.withImage';
